CREATE TABLE Models (
	id NVARCHAR(400) PRIMARY KEY,
	name TEXT NOT NULL,
	model_code TEXT NOT NULL,
	date_range TEXT NOT NULL,
);

--DROP TABLE Models
--CREATE TABLE [34] ([dateRange] NVARCHAR(100))
--ALTER TABLE [34] ADD ['REAR TIRE'] nvarchar(255)
--DROP TABLE KEYS2
--SELECT * FROM [671440]

--CREATE TABLE KEYS2 (
--name NVARCHAR(100) NOT NULL,
--age INT NOT NULL
--)

--CREATE UNIQUE INDEX IX_Keys_Name ON KEYS2 (name,age)



--INSERT INTO KEYS (name,age) VALUES ('John', 21)

--DROP TABLE [671440]
--SELECT * FROM [117520]

--SELECT  'DROP TABLE [' + name + '];'
--FROM    sys.tables

